### ISSUE TITLE
Generator should create files under a new directory

### ISSUE THREAD

**Issue by blzaugg** [metal/generator-metal#6]
Generator should create class files under a new directory of the same name.

 1. `$ yo metal`
 1. `? How do you want to name your class? (Modal)`
 2. Enter: `awesome`
 3. Follow prompts.

**Expected Result:**
All files generated under a new directory named `metal-awesome`.

**Actual Result:**
All files generated under current path.

**Comment by mairatma** [comment]
Agreed, it's an extra trouble to have to create the directory yourself, will work on this
